---
#
# Playbook to install the ELK stack + Beats
#
- hosts: elkservers
  remote_user: ubuntu
  become: yes
  become_user: root

# 
# Installing Java 8
#

# Add the Java repo

- name: Add the Java PPA repo
  apt_repository:
   repo: ppa:webupd8team/java

# Accept Oracle license

- name: Automatically accept the Oracle license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

# Install Java

- name: Install Java 8
  apt:
   name: oracle-java8-installer
   state: present
   update_cache: yes


# 
# Installing Elasticsearch
#

# Add Elasticsearch apt key

- name: Add Elasticsearch apt key
  apt_key:
   url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
   state: present

# Add the Elasticsearch apt repo. For versions 6 of the stack - use '6.x-prerelease':

- name: Adding Elasticsearch repo
  apt_repository:
   repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
   state: present

# Installing Elasticsearch

- name: Install Elasticsearch
  apt:
   name: elasticsearch
   update_cache: yes

# Update Elasticsearch config file to allow access (to secure Elasticsearch, bind to 'localhost').

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'network.host:'
   line: 'network.host: 0.0.0.0'

# Update Elasticsearch port in config file

- name: Updating the port in config file
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'http.port:'
   line: 'http.port: 9200'

# Start Elasticsearch
- name: Starting Elasticsearch
  service:
   name: elasticsearch
   state: started


# 
# Installing Kibana
#

# Install Kibana

- name: Install Kibana with apt
  apt:
   name: kibana
   update_cache: yes

# Configurations

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.host:'
   line: 'server.host: 0.0.0.0'

- name: Defining server port
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.port:'
   line: 'server.port: 5601'

- name: Defining Elasticsearch URL
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'elasticsearch.url:'
   line: 'elasticsearch.url: "http://localhost:9200"'

# Starting Kibana

- name: Starting Kibana
  service:
   name: kibana
   state: started

